org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_id=cell4
mod_name=Cell4
mod_license=MIT
mod_version=1.0.3
mod_group_id=com.cell4
mod_authors=Cell4
mod_description=AE2 addon adding Infinity Cells that support filtering by item, tag, and mod ID.

minecraft_version=26.1.2
minecraft_version_range=[26.1.2,)
neo_version=26.1.2.55-beta
neo_version_range=[26.1.2.55-beta,)
loader_version_range=[4,)

ae2_version=26.1.8-alpha
guideme_version=26.1.10-alpha
