modLoader="javafml"
loaderVersion="[47,48)"
license="MIT"

[[mods]]
modId="cell4"
version="${file.jarVersion}"
displayName="Cell\u2074 (Forge)"
authors="Cell4"
description='''
An AE2 addon adding Infinity Cells that support filtering by item, tag, and mod ID.'''

[[dependencies.cell4]]
modId="forge"
mandatory=true
versionRange="[47,48)"
ordering="NONE"
side="BOTH"

[[dependencies.cell4]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.cell4]]
modId="ae2"
mandatory=true
versionRange="[15.0.0,16.0.0)"
ordering="AFTER"
side="BOTH"
